name: Main Workflow

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]') || github.event_name == 'release'"
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Release]
    steps:
    - uses: actions/checkout@v3.5.2
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1
    - name: MSBuild
      shell: cmd
      run: |        
        msbuild _sources\FontGen.sln /t:Rebuild /p:Configuration=${{ matrix.Configuration }}
    - name: Prepare artifacts
      shell: cmd
      run: |
        set OGSR_ARTIFACT_NAME=Fonts_generator_1.${{ github.run_number }}.7z
        
        cd .\Bin
        
        7z a -t7z -m0=LZMA2:d=96m:fb=273 -mx=9 -mmt=2 ..\%OGSR_ARTIFACT_NAME% .\
    - name: Upload OGSR artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Fonts_generator_1.${{ github.run_number }}.7z
        path: .\Fonts_generator_1.${{ github.run_number }}.7z

    - name: Upload release asset
      if: github.event_name == 'release'
      uses: tanyagray/action-upload-release-asset@v1.1.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: .\Fonts_generator_1.${{ github.run_number }}.7z
        asset_name: Fonts_generator_1.${{ github.run_number }}.7z
        asset_content_type: application/zip
